name: Build Docs

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: v16
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - run: pnpm i && cd packages/schema-org && pnpm build
      - run: cd packages/vite && pnpm build
      - run: cd ./fixtures/nuxt/ && pnpm install

      - name: Install Docs Dependencies
        run: cd ./docs && pnpm install

      - name: PNPM build
        run: pnpm run build

      - name: Build docs
        run: pnpm docs:build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './docs/.vitepress/dist'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "New Release Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEMO_SITE_ID }}
        timeout-minutes: 1
